namespace MVFC.SQLCraft.Tests.Firebird;

[Collection("Firebird")]
public sealed class FirebirdTests(FirebirdContainerFixture fixture) : IClassFixture<FirebirdContainerFixture>
{
    private readonly FirebirdCraftDriver _driver = new(fixture.ConnectionString);

    [Fact]
    public void Testar_Insert_E_Select_PorId()
    {
        _driver.Execute("CREATE TABLE Persons (Id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, Name VARCHAR(100) NOT NULL)");

        TestHelpers.ExecuteOperations(_driver);
    }

    [Fact]
    public async Task Testar_Update_E_Select()
    {
        await _driver.ExecuteAsync("CREATE TABLE Persons2 (Id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, Name VARCHAR(100) NOT NULL)", ct: TestContext.Current.CancellationToken);

        await TestHelpers.ExecuteOperationsAsync(_driver, TestContext.Current.CancellationToken);
    }
}
